import React from 'react';
import Slideshow from '../Components/Slideshow'
const Movies = () => {
  return (
    <div className="slideshow-Movies">
		<div className="Movie-DIV-HOLDER">
			<h1 className="Live-Movie-HEAD">BatFamily in Live Action and Animated Movies</h1>
			<Slideshow ImageOne="https://flxt.tmsimg.com/assets/p838_p_v10_ay.jpg" ImageTwo="https://upload.wikimedia.org/wikipedia/en/5/5a/Batman_%281989%29_theatrical_poster.jpg" ImageThree="https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_.jpg" ImageFour="https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg" ImageFive="https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_.jpg" ImageSix="https://upload.wikimedia.org/wikipedia/en/a/af/Batman_Begins_Poster.jpg" ImageSeven="https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg" ImageEight="https://upload.wikimedia.org/wikipedia/en/8/83/Dark_knight_rises_poster.jpg" ImageNine="https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg"/>
		</div>
		<div className="Movie-DIV-HOLDER">
			<Slideshow ImageOne="https://upload.wikimedia.org/wikipedia/en/e/ea/Batman_mask_of_the_phantasm_poster.jpg" ImageTwo="https://m.media-amazon.com/images/M/MV5BOTQ0NmUzMzAtODk5My00MzYwLThlYWEtY2NkOGNhODg5ZmY1XkEyXkFqcGdeQXVyNjExODE1MDc@._V1_FMjpg_UX1000_.jpg" ImageThree="https://upload.wikimedia.org/wikipedia/en/f/fd/Batman_Beyond_-_Return_of_the_Joker_poster.jpg" ImageFour="https://m.media-amazon.com/images/M/MV5BN2IwYTVlZGQtOTRhNy00MDI5LThmMTUtYWI1MGUwMGFkYzI1XkEyXkFqcGdeQXVyNzQzNzQxNzI@._V1_.jpg" ImageFive="https://m.media-amazon.com/images/M/MV5BMTkyMTMwNjA3MV5BMl5BanBnXkFtZTcwNzE2NTI2OQ@@._V1_.jpg" ImageSix="https://upload.wikimedia.org/wikipedia/en/f/f0/Batman_Gotham_Knight.jpg" ImageSeven="https://m.media-amazon.com/images/M/MV5BNmY4ZDZjY2UtOWFiYy00MjhjLThmMjctOTQ2NjYxZGRjYmNlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" ImageEight="https://m.media-amazon.com/images/M/MV5BNTJjMmVkZjctNjNjMS00ZmI2LTlmYWEtOWNiYmQxYjY0YWVhXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" ImageNine="https://m.media-amazon.com/images/M/MV5BMzIxMDkxNDM2M15BMl5BanBnXkFtZTcwMDA5ODY1OQ@@._V1_FMjpg_UX1000_.jpg"/>
		</div>
		<div className="Movie-DIV-HOLDER">
			<Slideshow ImageOne="https://m.media-amazon.com/images/M/MV5BYTEzMmE0ZDYtYWNmYi00ZWM4LWJjOTUtYTE0ZmQyYWM3ZjA0XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg" ImageTwo="https://m.media-amazon.com/images/M/MV5BYjdkZWFhNzctYmNhNy00NGM5LTg0Y2YtZWM4NmU2MWQ3ODVkXkEyXkFqcGdeQXVyNTA0OTU0OTQ@._V1_.jpg" ImageThree="https://m.media-amazon.com/images/M/MV5BZDU1ZGRiY2YtYmZjMi00ZDQwLWJjMWMtNzUwNDMwYjQ4ZTVhXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" ImageFour="https://upload.wikimedia.org/wikipedia/en/thumb/0/00/Bat_vs_robin_cover.jpg/220px-Bat_vs_robin_cover.jpg" ImageFive="https://m.media-amazon.com/images/M/MV5BZWZiZmZhYmQtYjVkZi00MWIzLWEzM2MtYzhkNjliNzc2MTMwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" ImageSix="https://m.media-amazon.com/images/M/MV5BMTdjZTliODYtNWExMi00NjQ1LWIzN2MtN2Q5NTg5NTk3NzliL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg" ImageSeven="https://m.media-amazon.com/images/M/MV5BNTQzM2JkYTAtY2ExNi00N2ZhLWE5NDctMDQyMWU5ZjcwZDEwXkEyXkFqcGdeQXVyMjM5NDQzNTk@._V1_.jpg" ImageEight="https://m.media-amazon.com/images/M/MV5BYTJhNjYyMGItODdhOC00ZTZmLTk1MTMtZDRhMmZkYTRiOGJkXkEyXkFqcGdeQXVyMTg2NjYzOA@@._V1_.jpg" ImageNine="https://m.media-amazon.com/images/M/MV5BYWY5ODhlMWQtNDRiMC00MDk0LTgyMDItYmRmYWFkMjdmYWFmXkEyXkFqcGdeQXVyNTA4NzExMDg@._V1_.jpg"/>
		</div>
		<div className="Movie-DIV-HOLDER">
			<Slideshow ImageOne="https://m.media-amazon.com/images/M/MV5BOWExMjU1OTctNGIwZS00MjY2LWE2YWUtZWVlOTRjZDFhODVjXkEyXkFqcGdeQXVyMTEyNzgwMDUw._V1_.jpg" ImageTwo="https://m.media-amazon.com/images/M/MV5BYTZkZTM0NjYtN2Q2OS00YThjLWFkYTAtZDAwOWM3NjY1YjlhXkEyXkFqcGdeQXVyMTEyNzgwMDUw._V1_.jpg" ImageThree="https://m.media-amazon.com/images/M/MV5BMjJlMmI5YzAtNzY4YS00YzMzLTk0ZDAtMjUwMWU0OTdhYTkzXkEyXkFqcGdeQXVyMDEyMDU1Mw@@._V1_.jpg" ImageFour="https://m.media-amazon.com/images/M/MV5BZDc5NTFiMzgtZWJiOS00N2M1LWJmOGYtZmNjMzFhMzcxZjRiXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" ImageFive="https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/TTG_Movie_Poster_5.jpg/220px-TTG_Movie_Poster_5.jpg" ImageSix="https://cdn.flickeringmyth.com/wp-content/uploads/2020/12/Batman-Soul-of-the-Dragon.jpg" ImageSeven="https://m.media-amazon.com/images/M/MV5BZWNhNzk2YjItOWZiZC00ZGM0LTg2NjUtYzgwYWQzNjk0NjlmXkEyXkFqcGdeQXVyMTEyNzgwMDUw._V1_.jpg" ImageEight="https://m.media-amazon.com/images/M/MV5BYzk0MTI0YmUtMDgwOC00M2U5LTgzMDktM2RhN2M3ZDVmOWFiXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg" ImageNine="https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_.jpg"/>
		</div>
		<div className="Movie-DIV-HOLDER">
			<Slideshow ImageOne="https://upload.wikimedia.org/wikipedia/en/d/d4/Jla_doom_2012.jpg" ImageTwo="https://upload.wikimedia.org/wikipedia/en/f/f4/Justice_League-War.jpg" ImageThree="https://m.media-amazon.com/images/M/MV5BNzljNmZiNTktMTU4Ni00MTE2LWFmOTctYzY1NWJlY2ZiZjA3XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" ImageFour="https://m.media-amazon.com/images/M/MV5BMTk5ODdkYzQtMDFjYS00YjgwLWI2N2EtZmU1MWRmMzFiNzdjXkEyXkFqcGdeQXVyNDQ0MTYzMDA@._V1_.jpg" ImageFive="https://upload.wikimedia.org/wikipedia/en/d/d5/Justice_League_-_The_Flashpoint_Paradox.jpg" ImageSix="https://upload.wikimedia.org/wikipedia/en/3/3f/Newfrontier2.jpg" ImageSeven="https://m.media-amazon.com/images/M/MV5BMmNkMGU4YzEtZTdhZS00YzBhLTgzYzAtZWM2NTQ0ZGU2ZjM3XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" ImageEight="https://m.media-amazon.com/images/M/MV5BZDNjMjE5YmUtOTUwOC00MjAyLWJmMzktZjlkMjQyYzNiNmU3XkEyXkFqcGdeQXVyNTA4NzExMDg@._V1_.jpg" ImageNine="https://upload.wikimedia.org/wikipedia/en/8/81/JLA_Adventures-Trapped_in_Time.jpg"/>
		</div>
		<div className="Movie-DIV-HOLDER">
			<Slideshow ImageOne="https://m.media-amazon.com/images/M/MV5BYzA3ZmI1NzMtMTcxMi00ODg4LWFhMGItMTE2ZjIxODUzZTFiXkEyXkFqcGdeQXVyMTA1NzAwODMz._V1_.jpg" ImageTwo="https://m.media-amazon.com/images/M/MV5BMzg0ODZjNjUtNmVhZi00NTYxLWExNWMtMWI3MDFiMjhiNjc2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" ImageThree="https://upload.wikimedia.org/wikipedia/en/9/9e/Justice_League_-_Throne_of_Atlantis.jpg" ImageFour="https://m.media-amazon.com/images/M/MV5BMjk3ODhmNjgtZjllOC00ZWZjLTkwYzQtNzc1Y2ZhMjY2ODE0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" ImageFive="https://m.media-amazon.com/images/M/MV5BMDFiYTBkOGQtZjAwNi00OGMwLTg0YzQtNjI5YmFlZjY3ZWM3XkEyXkFqcGdeQXVyNTA0OTU0OTQ@._V1_.jpg" ImageSix="https://upload.wikimedia.org/wikipedia/en/4/4f/Teen_Titans_The_Judas_Contract.jpg" ImageSeven="https://m.media-amazon.com/images/M/MV5BMjQ4Njk5ODMtNjZhMC00OTRjLTg3NzktYjViNmE1ZWE5MzhlXkEyXkFqcGdeQXVyMTEyNzgwMDUw._V1_.jpg" ImageEight="https://m.media-amazon.com/images/M/MV5BYjI3NDg0ZTEtMDEwYS00YWMyLThjYjktMTNlM2NmYjc1OGRiXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg" ImageNine="https://images-na.ssl-images-amazon.com/images/I/81KX513BQxL.jpg"/>
		</div>
    </div>
  );
};

export default Movies;
